bot:
  name: cyber_anny_bot
  locale: RU
  photoDestinationDir: ./training
  token: no cheese for u bro

cnn:
  modelPath: "model_russian_6x6_kernel_darknet_92.bin"
  cnnInputLayerSize:
    width: 224
    height: 244
    channels: 3