bot:
  name: cyber_anny_bot
  locale: RU
  token: no cheese for u bro

cnn:
  modelFileName: "model_russian_6x6_kernel_darknet_93.bin"
  cnnInputLayerSize:
    width: 224
    height: 244
    channels: 3