package com.github.sbaldin.helpers

import com.elbekD.bot.types.Chat
import com.elbekD.bot.types.Message

object MessageProvider {

    fun message(messageId: Int, dateInSeconds: Int, text: String) = Message(
        message_id = messageId,
        from = null,
        sender_chat = null,
        date = dateInSeconds,
        chat = Chat(
            id = 1L,
            type = "test chat",
            title = null,
            username = null,
            first_name = null,
            last_name = null,
            photo = null,
            bio = null,
            description = null,
            invite_link = null,
            pinned_message = null,
            permissions = null,
            slow_mode_delay = null,
            sticker_set_name = null,
            can_set_sticker_set = null,
            linked_chat_id = null,
            location = null,
        ),
        forward_from = null,
        forward_from_chat = null,
        forward_from_message_id = null,
        forward_signature = null,
        forward_sender_name = null,
        forward_date = null,
        reply_to_message = null,
        via_bot = null,
        edit_date = null,
        media_group_id = null,
        author_signature = null,
        text = text,
        entities = null,
        animation = null,
        audio = null,
        document = null,
        photo = null,
        sticker = null,
        video = null,
        video_note = null,
        voice = null,
        caption = null,
        caption_entities = null,
        contact = null,
        dice = null,
        game = null,
        poll = null,
        venue = null,
        location = null,
        new_chat_members = null,
        left_chat_member = null,
        new_chat_title = null,
        new_chat_photo = null,
        delete_chat_photo = null,
        group_chat_created = null,
        supergroup_chat_created = null,
        channel_chat_created = null,
        migrate_to_chat_id = null,
        migrate_from_chat_id = null,
        pinned_message = null,
        invoice = null,
        successful_payment = null,
        connected_website = null,
        passport_data = null,
        proximity_alert_triggered = null,
        reply_markup = null,
    )
}
